# Data Preprocessing Tools

## Project Description
A small toy robots company in the US purchases various electronic components. The company decides to close its business with some of these suppliers. The file "BusinessData.csv" summarizes these data.  
In this exercise, we learn how to import the data, review and check them, taking care of missing data, deal with outliers, encode categorical data, etc. 

## Importing the Libraries

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the Dataset

In [40]:
dataset = pd.read_csv('SuppliersData.csv')

## Showing the Dataset in a Table

In [41]:
pd.DataFrame(dataset)

Country  Number of Parts  Cost ($) Business Continues
0  Brazil             44.0   72000.0                 No
1  Mexico             27.0   48000.0                Yes
2  Canada             30.0   54000.0                 No
3  Mexico             38.0   61000.0                 No
4  Canada             40.0       NaN                Yes
5  Brazil             35.0   58000.0                Yes
6  Mexico              NaN   52000.0                 No
7  Brazil             48.0   79000.0                Yes
8  Canada             50.0   83000.0                 No
9  Brazil             37.0   67000.0                Yes

## A Quick Review of the Data

In [42]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Country             10 non-null     object 
 1   Number of Parts     9 non-null      float64
 2   Cost ($)            9 non-null      float64
 3   Business Continues  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


## Seperate The Input and Output
Here, we put the independent variables in X and the dependent variable in y. 

In [43]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Showing the Input Data in a Table format

In [44]:
pd.DataFrame(X)

0    1      2
0  Brazil   44  72000
1  Mexico   27  48000
2  Canada   30  54000
3  Mexico   38  61000
4  Canada   40    NaN
5  Brazil   35  58000
6  Mexico  NaN  52000
7  Brazil   48  79000
8  Canada   50  83000
9  Brazil   37  67000

## A Quick Check of the Output Data

In [45]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [46]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [47]:
# A quick check
print(X)

[['Brazil' 44.0 72000.0]
 ['Mexico' 27.0 48000.0]
 ['Canada' 30.0 54000.0]
 ['Mexico' 38.0 61000.0]
 ['Canada' 40.0 63777.77777777778]
 ['Brazil' 35.0 58000.0]
 ['Mexico' 38.77777777777778 52000.0]
 ['Brazil' 48.0 79000.0]
 ['Canada' 50.0 83000.0]
 ['Brazil' 37.0 67000.0]]


## Encoding Categorical Data

### Encoding the Independent Variable

In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)

In [50]:
# A quick check
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [52]:
# a qucik check
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Feature Scaling

In [54]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:, 3:] = sc.fit_transform(X[:, 3:])

## Splitting the Dataset into the Training set and Test set

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [56]:
print(X_train)

[[0.0 0.0 1.0 0.0 -1.0735697969752662]
 [0.0 1.0 0.0 0.17760889313808945 6.632191985654332e-16]
 [1.0 0.0 0.0 0.758874361590019 0.7494732544921677]
 [0.0 0.0 1.0 -0.1130238410878753 -0.253200423814921]
 [0.0 0.0 1.0 -1.7115038793306814 -1.4381784072687531]
 [1.0 0.0 0.0 1.3401398300419485 1.3875383225057696]
 [0.0 1.0 0.0 1.6307725642679132 1.7521469327992565]
 [1.0 0.0 0.0 -0.5489729424268225 -0.5266568815350361]]


In [57]:
print(X_test)

[[0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285229]
 [1.0 0.0 0.0 -0.2583402082008577 0.29371249162530916]]


In [58]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [59]:
print(y_test)

[0 1]


In [60]:
print(X_train)

[[0.0 0.0 1.0 0.0 -1.0735697969752662]
 [0.0 1.0 0.0 0.17760889313808945 6.632191985654332e-16]
 [1.0 0.0 0.0 0.758874361590019 0.7494732544921677]
 [0.0 0.0 1.0 -0.1130238410878753 -0.253200423814921]
 [0.0 0.0 1.0 -1.7115038793306814 -1.4381784072687531]
 [1.0 0.0 0.0 1.3401398300419485 1.3875383225057696]
 [0.0 1.0 0.0 1.6307725642679132 1.7521469327992565]
 [1.0 0.0 0.0 -0.5489729424268225 -0.5266568815350361]]


In [61]:
print(X_test)

[[0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285229]
 [1.0 0.0 0.0 -0.2583402082008577 0.29371249162530916]]
