____
<a href='https://aintelligentmanufacturing.com/'><img src='Files\MANU465Logo2.png' width=250 height=250/></a>

# NumPy Documentation
<a href='https://numpy.org/doc/stable/user/absolute_beginners.html'><img src='Files\NumPyLogo.jpg' width=250 height=250/></a>

# To Install Numpy Library
Run Anaconda Prompt, then type:
> conda install numpy

> pip install numpy 

# Numpy Array

In [1]:
X=[1,2,3,4] # This is a list

In [2]:
type(X)

list

In [7]:
import numpy as np

In [8]:
X=np.array(X) # Convert the list to an Array 

In [9]:
X

array([1, 2, 3, 4])

In [10]:
# A 2D Array (a Matrix)
Y=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# To find the size of an Array
Y.shape

(3, 3)

##### Note: You can Shift+Tab to see the documentation of a function 
For example, Type np.arrange(), then Shift+Tab

# Create an Array

In [13]:
np.arange(0,10) # default step is 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10, 0.2)  # Create an Array between 0 to 10-step, with step=0.2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [14]:
np.linspace(0,10, 20)  # Create an Array of size 20 between 0 to 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
# create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# Create a random Array 
np.random.rand(10)

array([6.32554773e-01, 9.85554959e-01, 5.84759088e-01, 1.95388491e-01,
       5.04159256e-01, 6.72868242e-01, 7.36657896e-01, 1.55292030e-04,
       8.90226994e-01, 7.77401398e-01])

In [19]:
# Create a random 2D Array
R=np.random.rand(5,5)
R

array([[0.55373261, 0.86286734, 0.82459599, 0.13266039, 0.51913822],
       [0.73779917, 0.62531583, 0.38248021, 0.58825354, 0.17643355],
       [0.99070977, 0.66425049, 0.57347418, 0.13998098, 0.59540599],
       [0.71895653, 0.82227071, 0.934138  , 0.52875518, 0.98095342],
       [0.01234742, 0.02466047, 0.95117657, 0.81586192, 0.79193354]])

In [27]:
# Get a random Array from a Normal Distribution
N=np.random.randn(100)

In [28]:
# A Random Array of Integer Numbers
np.random.randint(0,100,10)

array([25, 33, 22, 19, 41,  9, 92,  2, 77, 26])

# Reshape an Array

In [29]:
a=np.arange(24)

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
len(a)

24

In [32]:
A=a.reshape(4,6)  # Note that (Number of Rows x Number of columns) must be equal to length of a

In [33]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# Find Max and Min and their index

In [34]:
# Consider the array N we created above
N.max()

2.8142591455386348

In [35]:
N.min()

-2.606131116631663

In [41]:
E=np.random.randint(0,100,10)

In [42]:
E

array([70,  0, 52, 33, 13, 38, 66, 16, 72, 40])

In [43]:
E.max()

72

In [44]:
E.argmax() # Give the Position (index) of the Max Number

8

# Other Useful Attributes

In [45]:
E.shape

(10,)

In [46]:
A.shape

(4, 6)

In [47]:
A.dtype

dtype('int32')

In [48]:
N.dtype

dtype('float64')

# Numpy Indexing

In [51]:
X=[7,11,25,8,42,55,9,7,0,-45]
X=np.array(X)
X

array([  7,  11,  25,   8,  42,  55,   9,   7,   0, -45])

In [52]:
X[0]

7

In [53]:
X[9]

-45

In [54]:
X[3:8] # all values from 3rd to (8-1)th 

array([ 8, 42, 55,  9,  7])

In [55]:
X[:5] # defualt start is 0

array([ 7, 11, 25,  8, 42])

In [56]:
X[4:] # default end is last one

array([ 42,  55,   9,   7,   0, -45])

In [57]:
X[-1]  # means last one

-45

In [58]:
X[:-1] # means all except last one

array([ 7, 11, 25,  8, 42, 55,  9,  7,  0])

In [59]:
X[1:] # means all except first

array([ 11,  25,   8,  42,  55,   9,   7,   0, -45])

In [60]:
NewX=X
NewX[0:4]=100  # replace from 0 to (4-1)rd elements with 100
NewX

array([100, 100, 100, 100,  42,  55,   9,   7,   0, -45])

In [62]:
X # Note that our original X also has changed; if you want to avoid this you must make a copy of the original
#   using the copy method, shown below


array([100, 100, 100, 100,  42,  55,   9,   7,   0, -45])

In [63]:
# Let's make the X again
X=[7,11,25,8,42,55,9,7,0,-45]
X=np.array(X)
X

array([  7,  11,  25,   8,  42,  55,   9,   7,   0, -45])

In [64]:
NewX=X.copy()

In [65]:
NewX

array([  7,  11,  25,   8,  42,  55,   9,   7,   0, -45])

In [66]:
NewX[0:4]=100  # replace from 0 to (4-1)rd elements with 100
NewX

array([100, 100, 100, 100,  42,  55,   9,   7,   0, -45])

In [67]:
X # As you can see now, the original X is intact. 

array([  7,  11,  25,   8,  42,  55,   9,   7,   0, -45])

# Indexing 2D Array

In [68]:
A=np.array([[1,2,3],[4,5,6]])

In [69]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
A.shape

(2, 3)

## Method 1

In [75]:
A[0][0]

1

In [76]:
A[0][2]

3

In [77]:
A[1][2]

6

In [78]:
A[0]

array([1, 2, 3])

## A Better Method

In [79]:
A[0,2]

3

In [80]:
A[0,:] # Grab first row

array([1, 2, 3])

In [81]:
A[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [82]:
A[:,0] # Grab first column

array([1, 4])

# Conditional Selection

In [83]:
X=np.array([5,7,1,0,4,-8,11,254,44])

In [84]:
X5=X[X>5]

In [85]:
X5

array([  7,  11, 254,  44])

In [87]:
B=np.arange(50)

In [88]:
B=B.reshape(5,10)

In [89]:
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [90]:
B[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [91]:
B10=B[B>10]

In [92]:
B10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

# Array Operations

In [93]:
C=np.arange(0,10)

In [94]:
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
C2=C+C
print(C2)

[ 0  2  4  6  8 10 12 14 16 18]


In [96]:
CM=C*C
print(CM)

[ 0  1  4  9 16 25 36 49 64 81]


In [98]:
CD=C/C  # Note, since we have 0/0 , we get a warning

<ipython-input-98-a86c1e558cbe>:1: RuntimeWarning: invalid value encountered in true_divide
  CD=C/C  # Note, since we have 0/0 , we get a warning, but still we can run the code


In [99]:
print(CD)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [100]:
CA=C+100
print(CA)

[100 101 102 103 104 105 106 107 108 109]


In [101]:
CI=1/C

<ipython-input-101-8f3a4db95573>:1: RuntimeWarning: divide by zero encountered in true_divide
  CI=1/C


In [102]:
print(CI)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


In [103]:
CP=C**2
print(CP)

[ 0  1  4  9 16 25 36 49 64 81]


In [104]:
CC=C**0.5
print(CC)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [105]:
CC2=np.sqrt(C)
print(CC2)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [107]:
CE=np.exp(C)
print(CE)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [109]:
CMax=np.max(C)
print('Maximum Value of this Array is ', CMax)

Maximum Value of this Array is  9


In [112]:
# Apply a Function to an Array
CS=np.sin(C)
CS

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

____
**Here you can find the list of all fuctions in NumPy**
<a href='https://numpy.org/doc/stable/reference/routines.math.html'><img src='Files\NumpyLogo.jpg' width=250 height=250/></a>
____

##### End